# fly.toml app configuration file generated for doomsdaytelegramorderbot on 2025-03-04T12:42:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'doomsdaytelegramorderbot'
primary_region = 'fra'

[deployment]
  region = "fra"  # Only use the Frankfurt region
  count = 1  # Only one machine

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
